### ISSUE TITLE
SIMM VERSION 2.7

### ISSUE THREAD

**Issue by NNazem** [OpenSourceRisk/Engine#275]
Hi everyone,
is the version 2.7 already available? Im trying to execute the example 44, but in the folder Example_44/Input i dont see the ore_SIMM.xml file for the 2.7, i only see ore_SIMM2.6_10D.xml.

**Comment by nvolfango** [comment]
See https://github.com/OpenSourceRisk/Engine/blob/master/Configurations/SIMM/simmcalibration_2.6.5.xml.

This is equivalent to 2.7 - it was 2.6.5 at the time that we added it, and has since been renamed (officially) to 2.7.

The example is only meant to demonstrate usage, not necessarily to provide the full scope of what we have! That said, feel free to add a PR extending the example if you like!

Thanks
